-- Listening Test Tables Schema

-- 1. Listening Tests Table
-- Stores the generated test metadata and questions (as JSON)
CREATE TABLE listening_tests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id VARCHAR2(50), -- ID of the teacher/admin who created it
    level_num NUMBER,
    topic VARCHAR2(200),
    question_count NUMBER,
    questions_json CLOB, -- JSON string containing all questions
    audio_url VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Test Assignments Table
-- Links students to tests and tracks progress
CREATE TABLE test_assignments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id NUMBER REFERENCES listening_tests(id) ON DELETE CASCADE,
    student_id VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'assigned', -- 'assigned', 'in_progress', 'completed'
    score NUMBER,
    answers_json CLOB, -- JSON string of student's answers
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_assignments_student ON test_assignments(student_id);
CREATE INDEX idx_tests_teacher ON listening_tests(teacher_id);
