const oracledb = require('oracledb');
const path = require('path');
require('dotenv').config();

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.autoCommit = true;

const dbConfig = {
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    connectString: process.env.DB_CONNECT_STRING
};

async function setupDatabase() {
    let connection;

    try {
        // Set TNS_ADMIN for Thin mode to locate wallet
        const walletPath = path.join(__dirname, 'wallet');
        process.env.TNS_ADMIN = walletPath;

        console.log('--- Debug Info ---');
        console.log('Wallet Path:', walletPath);
        console.log('DB_USER:', dbConfig.user ? dbConfig.user.substring(0, 3) + '***' : 'UNDEFINED');
        console.log('DB_CONNECT_STRING:', dbConfig.connectString);

        // Read tnsnames.ora
        const fs = require('fs');
        const tnsPath = path.join(walletPath, 'tnsnames.ora');
        if (fs.existsSync(tnsPath)) {
            console.log('tnsnames.ora found. Content preview:');
            const tnsContent = fs.readFileSync(tnsPath, 'utf8');
            console.log(tnsContent.substring(0, 200) + '...');
        } else {
            console.error('tnsnames.ora NOT found!');
        }
        console.log('------------------');

        console.log('Connecting to Oracle Database...');

        // Force use of wordtest_high if available, or fallback to env
        const connectString = 'wordtest_high';
        console.log(`Using Connect String: ${connectString}`);

        connection = await oracledb.getConnection({
            user: dbConfig.user,
            password: dbConfig.password,
            connectString: connectString,
            configDir: walletPath,
            walletLocation: walletPath,
            walletPassword: process.env.DB_WALLET_PASSWORD
        });

        console.log('Connected to Oracle Database!');

        // 1. Create Listening Tests Table
        console.log('Creating listening_tests table...');
        try {
            await connection.execute(`
                CREATE TABLE listening_tests (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    teacher_id VARCHAR2(50),
                    level_num NUMBER,
                    topic VARCHAR2(200),
                    question_count NUMBER,
                    questions_json CLOB,
                    audio_url VARCHAR2(500),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            `);
            console.log('✅ listening_tests table created.');
        } catch (err) {
            if (err.errorNum === 955) {
                console.log('⚠️ listening_tests table already exists.');
            } else {
                throw err;
            }
        }

        // 2. Create Test Assignments Table
        console.log('Creating test_assignments table...');
        try {
            await connection.execute(`
                CREATE TABLE test_assignments (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    test_id NUMBER REFERENCES listening_tests(id) ON DELETE CASCADE,
                    student_id VARCHAR2(50),
                    status VARCHAR2(20) DEFAULT 'assigned',
                    score NUMBER,
                    answers_json CLOB,
                    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP
                )
            `);
            console.log('✅ test_assignments table created.');
        } catch (err) {
            if (err.errorNum === 955) {
                console.log('⚠️ test_assignments table already exists.');
            } else {
                throw err;
            }
        }

        // 3. Create Indexes
        console.log('Creating indexes...');
        try {
            await connection.execute(`CREATE INDEX idx_assignments_student ON test_assignments(student_id)`);
            console.log('✅ idx_assignments_student created.');
        } catch (err) { if (err.errorNum !== 955) console.error(err); }

        try {
            await connection.execute(`CREATE INDEX idx_tests_teacher ON listening_tests(teacher_id)`);
            console.log('✅ idx_tests_teacher created.');
        } catch (err) { if (err.errorNum !== 955) console.error(err); }


    } catch (err) {
        console.error('Error setting up database:', err);
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error('Error closing connection:', err);
            }
        }
    }
}

setupDatabase();
